### ISSUE TITLE
entity 수정

### ISSUE THREAD

**Issue by lemphis** [ehago/kreamzone-api#11]
# PR [#7]에서 나온 추가 수정사항들 반영

<br>

## 완료 조건

- [x] `Brand entity 양방향 관계 삭제`
- [x] `FK name 추가 설정`
- [x] `BaseTime class를 abstract class로 변경`
- [x] `모든 테이블이 BaseTime class를 extend하도록 변경`
- [ ] `OneToMany 관계에 mapping한 List를 final로 변경`
- [ ] `각 entity의 private constructor에서 필요 없는 parameter 삭제`

<br>

## Reference
- JPA collection initialize 관련
[SOF](https://stackoverflow.com/questions/20715143/to-initialize-or-not-initialize-jpa-relationship-mappings)
[blog](http://wonwoo.ml/index.php/post/992)
---

## 체크리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [x] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 Label을 추가했는가?
- [x] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [ ] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?

---

**Comment by mintheon** [comment]
이야 공부 빡시하노. 덕분에 SOF 글 잘 보고갑니다.
